-- GarageSale MVP 初始数据结构：活动、郊区、公开查询和服务端限流。

create schema if not exists extensions;
create extension if not exists postgis schema extensions;

create or replace function public.sale_timezone(sale_state text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case sale_state
    when 'WA' then 'Australia/Perth'
    when 'NSW' then 'Australia/Sydney'
    when 'VIC' then 'Australia/Melbourne'
    when 'QLD' then 'Australia/Brisbane'
    when 'SA' then 'Australia/Adelaide'
    when 'TAS' then 'Australia/Hobart'
    when 'ACT' then 'Australia/Sydney'
    when 'NT' then 'Australia/Darwin'
    else 'Australia/Sydney'
  end
$$;

create table public.suburbs (
  id bigint generated by default as identity primary key,
  name text not null,
  state text not null check (state in ('WA', 'NSW', 'VIC', 'QLD', 'SA', 'TAS', 'ACT', 'NT')),
  postcode text not null check (postcode ~ '^[0-9]{4}$'),
  slug text not null unique,
  location extensions.geography(Point, 4326) not null,
  created_at timestamptz not null default now(),
  unique (name, state, postcode)
);

create index suburbs_location_gist_idx on public.suburbs using gist (location);
create index suburbs_name_search_idx on public.suburbs (lower(name) text_pattern_ops);
create index suburbs_postcode_idx on public.suburbs (postcode);

create table public.sales (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(trim(title)) between 1 and 80),
  description text check (description is null or char_length(description) <= 2000),
  address text not null check (char_length(trim(address)) > 0),
  suburb text not null check (char_length(trim(suburb)) > 0),
  state text not null check (state in ('WA', 'NSW', 'VIC', 'QLD', 'SA', 'TAS', 'ACT', 'NT')),
  postcode text not null check (postcode ~ '^[0-9]{4}$'),
  location extensions.geography(Point, 4326) not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  photos text[] not null default '{}',
  categories text[] not null default '{}',
  source text not null default 'self' check (source in ('self', 'gumtree', 'facebook', 'manual', 'other')),
  source_url text,
  contact_email text,
  manage_token uuid unique,
  status text not null default 'pending_verification' check (status in ('pending_verification', 'published', 'cancelled', 'removed')),
  email_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sales_time_order_check check (end_at > start_at),
  constraint sales_single_local_day_check check (
    (start_at at time zone public.sale_timezone(state))::date =
    (end_at at time zone public.sale_timezone(state))::date
  ),
  constraint sales_photo_count_check check (cardinality(photos) <= 6),
  constraint sales_photo_values_check check (array_position(photos, null) is null),
  constraint sales_categories_check check (
    categories <@ array[
      'furniture', 'tools', 'clothing', 'kids-baby', 'books-media',
      'electronics', 'garden', 'collectables', 'household', 'other'
    ]::text[]
  ),
  constraint sales_self_fields_check check (
    (
      source = 'self'
      and contact_email is not null
      and manage_token is not null
      and source_url is null
    )
    or
    (
      source <> 'self'
      and contact_email is null
      and manage_token is null
      and source_url is not null
    )
  ),
  constraint sales_verification_check check (
    (status = 'pending_verification' and email_verified_at is null)
    or status <> 'pending_verification'
  )
);

create index sales_location_gist_idx on public.sales using gist (location);
create index sales_state_suburb_idx on public.sales (state, suburb);
create index sales_start_at_idx on public.sales (start_at);
create index sales_status_end_at_idx on public.sales (status, end_at);
create index sales_contact_email_idx on public.sales (lower(contact_email)) where contact_email is not null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger sales_set_updated_at
before update on public.sales
for each row execute function public.set_updated_at();

alter table public.suburbs enable row level security;
alter table public.sales enable row level security;

create policy "公开读取郊区"
on public.suburbs
for select
to anon, authenticated
using (true);

create policy "公开读取有效活动"
on public.sales
for select
to anon, authenticated
using (status = 'published' and end_at > now());

revoke all on public.suburbs from anon, authenticated;
revoke all on public.sales from anon, authenticated;

grant select on public.suburbs to anon, authenticated;
grant select (
  id, title, description, address, suburb, state, postcode, location,
  start_at, end_at, photos, categories, source, source_url,
  status, email_verified_at, created_at, updated_at
) on public.sales to anon, authenticated;

create or replace view public.public_sales
with (security_invoker = true, security_barrier = true)
as
select
  id,
  title,
  description,
  address,
  suburb,
  state,
  postcode,
  extensions.st_x(location::extensions.geometry) as longitude,
  extensions.st_y(location::extensions.geometry) as latitude,
  start_at,
  end_at,
  photos,
  categories,
  source,
  source_url,
  created_at,
  updated_at
from public.sales
where status = 'published' and end_at > now();

revoke all on public.public_sales from anon, authenticated;
grant select on public.public_sales to anon, authenticated;

create or replace function public.get_upcoming_sales_near(
  search_longitude double precision,
  search_latitude double precision,
  radius_km integer default 25,
  window_end timestamptz default (now() + interval '14 days'),
  category_filters text[] default null
)
returns table (
  id uuid,
  title text,
  description text,
  address text,
  suburb text,
  state text,
  postcode text,
  longitude double precision,
  latitude double precision,
  start_at timestamptz,
  end_at timestamptz,
  photos text[],
  categories text[],
  source text,
  source_url text,
  distance_km double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    s.id,
    s.title,
    s.description,
    s.address,
    s.suburb,
    s.state,
    s.postcode,
    extensions.st_x(s.location::extensions.geometry),
    extensions.st_y(s.location::extensions.geometry),
    s.start_at,
    s.end_at,
    s.photos,
    s.categories,
    s.source,
    s.source_url,
    extensions.st_distance(
      s.location,
      extensions.st_setsrid(extensions.st_makepoint(search_longitude, search_latitude), 4326)::extensions.geography
    ) / 1000.0 as distance_km
  from public.sales s
  where s.status = 'published'
    and s.end_at > now()
    and s.start_at < window_end
    and extensions.st_dwithin(
      s.location,
      extensions.st_setsrid(extensions.st_makepoint(search_longitude, search_latitude), 4326)::extensions.geography,
      radius_km * 1000.0
    )
    and (category_filters is null or cardinality(category_filters) = 0 or s.categories && category_filters)
  order by s.start_at asc, distance_km asc
$$;

revoke all on function public.get_upcoming_sales_near(double precision, double precision, integer, timestamptz, text[]) from public;
grant execute on function public.get_upcoming_sales_near(double precision, double precision, integer, timestamptz, text[]) to anon, authenticated;

create table public.rate_limits (
  key_hash text not null,
  action text not null,
  window_started_at timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  expires_at timestamptz not null,
  primary key (key_hash, action, window_started_at)
);

alter table public.rate_limits enable row level security;
revoke all on public.rate_limits from anon, authenticated;

create or replace function public.consume_rate_limit(
  limit_key_hash text,
  limit_action text,
  max_requests integer,
  window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_window timestamptz;
  updated_count integer;
begin
  if max_requests <= 0 or window_seconds <= 0 then
    raise exception 'max_requests and window_seconds must be positive';
  end if;

  current_window := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / window_seconds) * window_seconds
  );

  insert into public.rate_limits (
    key_hash,
    action,
    window_started_at,
    request_count,
    expires_at
  ) values (
    limit_key_hash,
    limit_action,
    current_window,
    1,
    current_window + make_interval(secs => window_seconds)
  )
  on conflict (key_hash, action, window_started_at)
  do update set request_count = rate_limits.request_count + 1
  returning request_count into updated_count;

  return updated_count <= max_requests;
end;
$$;

revoke all on function public.consume_rate_limit(text, text, integer, integer) from public;
grant execute on function public.consume_rate_limit(text, text, integer, integer) to service_role;

create or replace function public.delete_expired_rate_limits()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  deleted_count integer;
begin
  delete from public.rate_limits where expires_at < now();
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function public.delete_expired_rate_limits() from public;
grant execute on function public.delete_expired_rate_limits() to service_role;
