-- 将公开活动、卖家私密信息、访问 token 和邮件投递拆分。

create extension if not exists pgcrypto with schema extensions;

create table public.sale_private_details (
  sale_id uuid primary key references public.sales(id) on delete cascade,
  contact_email text not null check (contact_email = lower(trim(contact_email))),
  retain_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index sale_private_details_email_idx
on public.sale_private_details (contact_email);

create trigger sale_private_details_set_updated_at
before update on public.sale_private_details
for each row execute function public.set_updated_at();

create table public.sale_access_tokens (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales(id) on delete cascade,
  purpose text not null check (purpose in ('verification', 'manage')),
  token_hash text not null check (token_hash ~ '^[0-9a-f]{64}$'),
  expires_at timestamptz not null,
  used_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  unique (purpose, token_hash)
);

create index sale_access_tokens_sale_idx
on public.sale_access_tokens (sale_id, purpose)
where revoked_at is null;

create table public.email_outbox (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('sale-verification', 'sale-recovery')),
  recipient text not null check (recipient = lower(trim(recipient))),
  payload jsonb not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'sent', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index email_outbox_pending_idx
on public.email_outbox (next_attempt_at, created_at)
where status in ('pending', 'failed');

create trigger email_outbox_set_updated_at
before update on public.email_outbox
for each row execute function public.set_updated_at();

create table public.moderation_events (
  id bigint generated by default as identity primary key,
  sale_id uuid not null references public.sales(id) on delete cascade,
  action text not null,
  actor_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.sale_private_details enable row level security;
alter table public.sale_access_tokens enable row level security;
alter table public.email_outbox enable row level security;
alter table public.moderation_events enable row level security;

revoke all on public.sale_private_details from anon, authenticated;
revoke all on public.sale_access_tokens from anon, authenticated;
revoke all on public.email_outbox from anon, authenticated;
revoke all on public.moderation_events from anon, authenticated;

insert into public.sale_private_details (sale_id, contact_email, retain_until)
select id, lower(trim(contact_email)), end_at + interval '90 days'
from public.sales
where contact_email is not null;

insert into public.sale_access_tokens (sale_id, purpose, token_hash, expires_at)
select
  id,
  'manage',
  encode(extensions.digest(manage_token::text, 'sha256'), 'hex'),
  greatest(end_at + interval '30 days', now() + interval '30 days')
from public.sales
where manage_token is not null;

insert into public.sale_access_tokens (sale_id, purpose, token_hash, expires_at)
select
  id,
  'verification',
  encode(extensions.digest(manage_token::text, 'sha256'), 'hex'),
  now() + interval '48 hours'
from public.sales
where manage_token is not null
  and status = 'pending_verification';

alter table public.sales drop constraint sales_self_fields_check;
alter table public.sales drop column contact_email;
alter table public.sales drop column manage_token;

create or replace function public.create_self_sale(
  p_title text,
  p_description text,
  p_address text,
  p_suburb text,
  p_state text,
  p_postcode text,
  p_longitude double precision,
  p_latitude double precision,
  p_start_at timestamptz,
  p_end_at timestamptz,
  p_photos text[],
  p_categories text[],
  p_contact_email text
)
returns table (
  sale_id uuid,
  manage_token text,
  verification_token text,
  outbox_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_sale_id uuid := gen_random_uuid();
  raw_manage_token text := encode(extensions.gen_random_bytes(32), 'hex');
  raw_verification_token text := encode(extensions.gen_random_bytes(32), 'hex');
  new_outbox_id uuid;
  normalized_email text := lower(trim(p_contact_email));
begin
  insert into public.sales (
    id, title, description, address, suburb, state, postcode, location,
    start_at, end_at, photos, categories, source, status
  ) values (
    new_sale_id,
    p_title,
    nullif(p_description, ''),
    p_address,
    p_suburb,
    p_state,
    p_postcode,
    extensions.st_setsrid(extensions.st_makepoint(p_longitude, p_latitude), 4326)::extensions.geography,
    p_start_at,
    p_end_at,
    coalesce(p_photos, '{}'),
    coalesce(p_categories, '{}'),
    'self',
    'pending_verification'
  );

  insert into public.sale_private_details (sale_id, contact_email, retain_until)
  values (new_sale_id, normalized_email, p_end_at + interval '90 days');

  insert into public.sale_access_tokens (sale_id, purpose, token_hash, expires_at)
  values
    (
      new_sale_id,
      'manage',
      encode(extensions.digest(raw_manage_token, 'sha256'), 'hex'),
      greatest(p_end_at + interval '30 days', now() + interval '30 days')
    ),
    (
      new_sale_id,
      'verification',
      encode(extensions.digest(raw_verification_token, 'sha256'), 'hex'),
      now() + interval '48 hours'
    );

  insert into public.email_outbox (kind, recipient, payload)
  values (
    'sale-verification',
    normalized_email,
    jsonb_build_object(
      'saleId', new_sale_id,
      'title', p_title,
      'manageToken', raw_manage_token,
      'verificationToken', raw_verification_token
    )
  )
  returning id into new_outbox_id;

  return query
  select new_sale_id, raw_manage_token, raw_verification_token, new_outbox_id;
end;
$$;

create or replace function public.verify_sale_token(raw_token text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  matched_sale_id uuid;
begin
  select token.sale_id
  into matched_sale_id
  from public.sale_access_tokens token
  join public.sales sale on sale.id = token.sale_id
  where token.purpose = 'verification'
    and token.token_hash = encode(extensions.digest(raw_token, 'sha256'), 'hex')
    and token.revoked_at is null
    and token.expires_at > now()
    and sale.status in ('pending_verification', 'published')
  for update of token;

  if matched_sale_id is null then
    return null;
  end if;

  update public.sale_access_tokens
  set used_at = coalesce(used_at, now())
  where sale_id = matched_sale_id
    and purpose = 'verification'
    and token_hash = encode(extensions.digest(raw_token, 'sha256'), 'hex');

  update public.sales
  set status = 'published', email_verified_at = coalesce(email_verified_at, now())
  where id = matched_sale_id
    and status = 'pending_verification';

  return matched_sale_id;
end;
$$;

create or replace function public.resolve_manage_sale_id(raw_token text)
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select token.sale_id
  from public.sale_access_tokens token
  join public.sales sale on sale.id = token.sale_id
  where token.purpose = 'manage'
    and token.token_hash = encode(extensions.digest(raw_token, 'sha256'), 'hex')
    and token.revoked_at is null
    and token.expires_at > now()
    and sale.status <> 'removed'
  limit 1
$$;

revoke all on function public.create_self_sale(text, text, text, text, text, text, double precision, double precision, timestamptz, timestamptz, text[], text[], text) from public;
revoke all on function public.verify_sale_token(text) from public;
revoke all on function public.resolve_manage_sale_id(text) from public;

grant execute on function public.create_self_sale(text, text, text, text, text, text, double precision, double precision, timestamptz, timestamptz, text[], text[], text) to service_role;
grant execute on function public.verify_sale_token(text) to service_role;
grant execute on function public.resolve_manage_sale_id(text) to service_role;

